BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Paper] ALTER COLUMN [receivedDate] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[Paper] ALTER COLUMN [approvedDate] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[Paper] ALTER COLUMN [publishdDate] NVARCHAR(1000) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
